#!/usr/bin/env python3
from __future__ import annotations

import argparse
import bisect
import json
from pathlib import Path

try:
    from tools.jp_event_inventory import EVENT_DATA_END, SCENARIO_COUNT, event_block_starts
except ModuleNotFoundError:  # Direct execution adds tools/, not the repository root, to sys.path.
    from jp_event_inventory import EVENT_DATA_END, SCENARIO_COUNT, event_block_starts


ENGLISH_RECORDS = Path("script_extract/english_records.json")
MACHINE_TRANSLATIONS = Path("script_extract/korean_records_google.json")
JSON_OUT = Path("localization/english_dialogue_mapping.json")
MARKDOWN_OUT = Path("docs/english_dialogue_mapping.md")


def load_records(path: Path) -> list[dict[str, object]]:
    records = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(records, list):
        raise ValueError(f"expected a record list in {path}")
    return records


def classify_records(
    japanese: bytes,
    english_records: list[dict[str, object]],
    machine_records: list[dict[str, object]],
) -> dict[str, object]:
    starts = event_block_starts(japanese)
    machine_by_index = {int(record["index"]): record for record in machine_records}
    scenarios: list[dict[str, object]] = [
        {
            "scenario": number,
            "block_start": f"0x{start:06X}",
            "block_end": f"0x{(starts[number] if number < SCENARIO_COUNT else EVENT_DATA_END):06X}",
            "records": [],
        }
        for number, start in enumerate(starts, 1)
    ]
    outside: list[dict[str, object]] = []
    seen_prefixes: set[int] = set()

    for record in english_records:
        index = int(record["index"])
        prefix = int(str(record["prefix"]), 16)
        if prefix in seen_prefixes:
            raise ValueError(f"duplicate English continuation prefix 0x{prefix:06X}")
        seen_prefixes.add(prefix)
        machine = machine_by_index.get(index, {})
        row = {
            "index": index,
            "english_address": str(record["address"]).upper().replace("0X", "0x"),
            "continuation_prefix": f"0x{prefix:06X}",
            "english_size": int(record["size"]),
            "english": str(record["text"]),
            "machine_korean_reference": str(machine.get("translation", "")),
            "translation_status": "reference_only",
        }
        scenario_index = bisect.bisect_right(starts, prefix) - 1
        if scenario_index >= 0:
            block_end = starts[scenario_index + 1] if scenario_index + 1 < len(starts) else EVENT_DATA_END
            if prefix < block_end:
                scenarios[scenario_index]["records"].append(row)
                continue
        outside.append(row)

    for scenario in scenarios:
        records = scenario["records"]
        scenario["record_count"] = len(records)
        indexes = sorted(int(record["index"]) for record in records)
        runs: list[list[int]] = []
        for index in indexes:
            if runs and index == runs[-1][1] + 1:
                runs[-1][1] = index
            else:
                runs.append([index, index])
        scenario["record_index_runs"] = runs

    return {
        "source": str(ENGLISH_RECORDS),
        "machine_translation_source": str(MACHINE_TRANSLATIONS),
        "mapping_semantics": (
            "continuation_prefix is the three-byte event continuation value preserved at the "
            "start of each English dialogue record; it assigns scenario ownership but is not "
            "the Japanese text-page address"
        ),
        "scenario_count": SCENARIO_COUNT,
        "record_count": len(english_records),
        "scenario_record_count": sum(int(item["record_count"]) for item in scenarios),
        "outside_event_record_count": len(outside),
        "scenarios": scenarios,
        "outside_event_blocks": outside,
    }


def markdown_report(result: dict[str, object]) -> str:
    lines = [
        "# English Dialogue Ownership Map",
        "",
        "Generated by `python3 tools/english_dialogue_inventory.py`.",
        "",
        "The English extraction is reference material, not an authoritative Japanese-ROM patch",
        "source. Its three-byte `prefix` is an event continuation value. It reliably assigns a",
        "record to a scenario block, but it is not the address of the corresponding Japanese text",
        "page. Machine Korean is retained only as a rough translation aid and must be reviewed.",
        "",
        f"- English records: {result['record_count']}",
        f"- Scenario-owned records: {result['scenario_record_count']}",
        f"- Ending/epilogue records outside event blocks: {result['outside_event_record_count']}",
        "",
        "| Scenario | Event block | English records | Record indexes |",
        "| ---: | --- | ---: | --- |",
    ]
    for item in result["scenarios"]:
        runs = item["record_index_runs"]
        indexes = "-" if not runs else ", ".join(
            str(start) if start == end else f"{start}..{end}" for start, end in runs
        )
        lines.append(
            f"| {item['scenario']} | `{item['block_start']}..{item['block_end']}` | "
            f"{item['record_count']} | {indexes} |"
        )
    lines.extend(
        [
            "",
            "Exact English text, continuation prefixes, and machine-reference strings are stored",
            "in `localization/english_dialogue_mapping.json`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Classify legacy English dialogue by Japanese event block")
    parser.add_argument("--jp-rom", type=Path, default=Path("roms/original/Langrisser II (Japan).md"))
    parser.add_argument("--english", type=Path, default=ENGLISH_RECORDS)
    parser.add_argument("--machine", type=Path, default=MACHINE_TRANSLATIONS)
    parser.add_argument("--json", type=Path, default=JSON_OUT)
    parser.add_argument("--markdown", type=Path, default=MARKDOWN_OUT)
    args = parser.parse_args()

    result = classify_records(
        args.jp_rom.read_bytes(), load_records(args.english), load_records(args.machine)
    )
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(markdown_report(result), encoding="utf-8")
    print(
        f"{result['scenario_record_count']} scenario records, "
        f"{result['outside_event_record_count']} outside-event records; "
        f"wrote {args.json} and {args.markdown}"
    )


if __name__ == "__main__":
    main()
