#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parents[1]))

from scripts import build_korean_jp_probe as builder


RESOURCE_TABLE = builder.BYTE_UI_FONT_RESOURCE_TABLE
KNOWN_OWNERS = {
    builder.BYTE_UI_FONT_RESOURCE_INDEX: "byte_ui_font",
}


def be32(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 4], "big")


def resource_pointers(data: bytes) -> list[int]:
    first_pointer = be32(data, RESOURCE_TABLE) & 0x00FFFFFF
    table_size = first_pointer - RESOURCE_TABLE
    if table_size <= 0 or table_size % 4:
        raise ValueError(
            f"invalid compressed resource table boundary: 0x{first_pointer:06X}"
        )
    count = table_size // 4
    pointers = [
        be32(data, RESOURCE_TABLE + index * 4) & 0x00FFFFFF
        for index in range(count)
    ]
    if pointers[0] != RESOURCE_TABLE + count * 4:
        raise ValueError("first compressed resource does not immediately follow its table")
    if any(left >= right for left, right in zip(pointers, pointers[1:])):
        raise ValueError("compressed resource pointers are not strictly increasing")
    if pointers[-1] >= len(data):
        raise ValueError("compressed resource table points beyond the ROM")
    return pointers


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def inventory(japanese: bytes, korean: bytes) -> dict[str, object]:
    original_pointers = resource_pointers(japanese)
    count = len(original_pointers)
    current_pointers = [
        be32(korean, RESOURCE_TABLE + index * 4) & 0x00FFFFFF
        for index in range(count)
    ]
    entries = []
    type_counts: dict[str, int] = {}
    total_decompressed_bytes = 0
    for index, (original_pointer, current_pointer) in enumerate(
        zip(original_pointers, current_pointers)
    ):
        original_type = japanese[original_pointer]
        current_type = korean[current_pointer]
        original_payload = builder.decompress_9dfe(japanese, original_pointer + 1)
        current_payload = builder.decompress_9dfe(korean, current_pointer + 1)
        original_hash = sha256(original_payload)
        current_hash = sha256(current_payload)
        pointer_modified = original_pointer != current_pointer
        content_modified = original_type != current_type or original_hash != current_hash
        type_key = str(original_type)
        type_counts[type_key] = type_counts.get(type_key, 0) + 1
        total_decompressed_bytes += len(original_payload)
        entries.append(
            {
                "index": index,
                "table_entry": f"0x{RESOURCE_TABLE + index * 4:06X}",
                "original_pointer": f"0x{original_pointer:06X}",
                "current_pointer": f"0x{current_pointer:06X}",
                "original_type": original_type,
                "current_type": current_type,
                "original_decompressed_size": len(original_payload),
                "current_decompressed_size": len(current_payload),
                "original_decompressed_sha256": original_hash,
                "current_decompressed_sha256": current_hash,
                "pointer_modified": pointer_modified,
                "content_modified": content_modified,
                "modified": pointer_modified or content_modified,
                "owner": KNOWN_OWNERS.get(index),
                "reviewed": False,
                "live_verified": False,
            }
        )
    return {
        "warning": (
            "A successfully decompressed resource is not necessarily text or UI. "
            "Ownership is recorded only when established independently."
        ),
        "resource_table": f"0x{RESOURCE_TABLE:06X}",
        "table_end": f"0x{original_pointers[0]:06X}",
        "entry_count": count,
        "type_counts": type_counts,
        "total_original_decompressed_bytes": total_decompressed_bytes,
        "modified_count": sum(bool(entry["modified"]) for entry in entries),
        "known_owner_count": sum(entry["owner"] is not None for entry in entries),
        "unknown_owner_count": sum(entry["owner"] is None for entry in entries),
        "entries": entries,
    }


def markdown_report(result: dict[str, object]) -> str:
    lines = [
        "# Compressed Resource Inventory",
        "",
        "Generated by `python3 tools/jp_compressed_resource_inventory.py`.",
        "",
        "The table boundary is derived from its first pointer. Every listed block was",
        "successfully decompressed with the game's `0x9DFE` decoder. Decompression alone",
        "does not establish that a block contains text or UI data.",
        "",
        f"- Resource table: `{result['resource_table']}`",
        f"- Table end / first resource: `{result['table_end']}`",
        f"- Entries: {result['entry_count']}",
        f"- Original decompressed bytes: {result['total_original_decompressed_bytes']:,}",
        f"- Modified resources in current build: {result['modified_count']}",
        f"- Known owners: {result['known_owner_count']}",
        f"- Unknown owners: {result['unknown_owner_count']}",
        "",
        "## Type Distribution",
        "",
        "| Type byte | Entries |",
        "| ---: | ---: |",
    ]
    for resource_type, count in sorted(
        result["type_counts"].items(), key=lambda item: int(item[0])
    ):
        lines.append(f"| `0x{int(resource_type):02X}` | {count} |")
    lines.extend(
        [
            "",
            "## Known And Modified Resources",
            "",
            "| Index | Owner | Original | Current | Type | Size | Pointer changed | Content changed |",
            "| ---: | --- | --- | --- | ---: | ---: | --- | --- |",
        ]
    )
    selected = [
        entry
        for entry in result["entries"]
        if entry["owner"] is not None or entry["modified"]
    ]
    for entry in selected:
        lines.append(
            f"| {entry['index']} | {entry['owner'] or ''} | `{entry['original_pointer']}` | "
            f"`{entry['current_pointer']}` | `0x{entry['original_type']:02X}` | "
            f"{entry['original_decompressed_size']} | {entry['pointer_modified']} | "
            f"{entry['content_modified']} |"
        )
    lines.extend(
        [
            "",
            "All pointers, sizes, decompressed hashes, ownership fields, and review flags",
            "are in `localization/compressed_resources.json`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Inventory the 0x9DFE compressed resource table")
    parser.add_argument("--jp-rom", type=Path, default=Path("roms/original/Langrisser II (Japan).md"))
    parser.add_argument(
        "--ko-rom",
        type=Path,
        default=Path("roms/builds/Langrisser II (Korean JP Probe).md"),
    )
    parser.add_argument("--json", type=Path, default=Path("localization/compressed_resources.json"))
    parser.add_argument("--markdown", type=Path, default=Path("docs/compressed_resource_inventory.md"))
    args = parser.parse_args()
    result = inventory(args.jp_rom.read_bytes(), args.ko_rom.read_bytes())
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(markdown_report(result), encoding="utf-8")
    print(
        f"{result['entry_count']} resources decompressed; "
        f"{result['modified_count']} modified; {result['unknown_owner_count']} owners unknown"
    )


if __name__ == "__main__":
    main()
