#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parents[1]))

from scripts import build_korean_jp_probe as builder
from tools.jp_text_font_analyzer import be16, be32


SCAN_END = 0x180000
MAX_GLYPH_ID = 0x07FF
CONTROLS = {0xFFF7, 0xFFFD, 0xFFFE}
TERMINATOR = 0xFFFF
MIN_GLYPHS = 3
MAX_WORDS = 64


def scan_candidates(data: bytes, start: int = 0, end: int = SCAN_END) -> list[tuple[int, list[int]]]:
    entries = []
    position = start
    while position + 1 < end:
        words = []
        glyph_count = 0
        cursor = position
        terminated = False
        while cursor + 1 < end and len(words) <= MAX_WORDS:
            value = be16(data, cursor)
            cursor += 2
            if value == TERMINATOR:
                terminated = True
                break
            if value in CONTROLS:
                words.append(value)
                continue
            if value > MAX_GLYPH_ID:
                break
            words.append(value)
            glyph_count += 1
        if terminated and MIN_GLYPHS <= glyph_count and len(words) <= MAX_WORDS:
            entries.append((position, words + [TERMINATOR]))
            position = cursor
        else:
            position += 2
    return entries


def read_current_stream(data: bytes, offset: int, limit: int = 256) -> list[int] | None:
    words = []
    for _ in range(limit):
        if offset + 1 >= len(data):
            return None
        value = be16(data, offset)
        words.append(value)
        offset += 2
        if value == TERMINATOR:
            return words
    return None


def pointer_owners(data: bytes) -> dict[int, str]:
    owners = {}
    groups = {
        "conditions": (0x098D7A, 32),
        "scenario_descriptions": (0x09CF7C, 31),
        "item_names": (0x0A1902, 38),
        "item_descriptions": (0x0A1D7C, 37),
    }
    for name, (table, count) in groups.items():
        for index in range(count):
            owners[be32(data, table + index * 4)] = f"{name}[{index}]"
    return owners


def declared_targets() -> dict[int, str]:
    targets = {
        offset: text
        for offset, text in builder.DIRECT_STRING_PATCHES.items()
        if offset < SCAN_END
    }
    for offset, (_, text) in builder.OPENING_TEXT_LIST_PATCHES.items():
        targets[offset] = text
    return targets


def tokens(words: list[int] | None) -> str | None:
    return None if words is None else " ".join(f"{word:04X}" for word in words)


def inventory(japanese: bytes, korean: bytes) -> dict[str, object]:
    owners = pointer_owners(japanese)
    targets = declared_targets()
    rows = []
    for offset, original in scan_candidates(japanese):
        current = read_current_stream(korean, offset)
        if offset in owners:
            ownership = "pointer_table_record"
        elif offset in targets:
            ownership = "declared_direct_patch"
        else:
            ownership = "unclassified_candidate"
        rows.append(
            {
                "address": f"0x{offset:06X}",
                "ownership": ownership,
                "owner": owners.get(offset),
                "target_korean": targets.get(offset),
                "original_word_count": len(original),
                "original_tokens": tokens(original),
                "current_tokens": tokens(current),
                "modified": current != original,
                "reviewed": False,
            }
        )
    counts = {
        category: sum(row["ownership"] == category for row in rows)
        for category in ("pointer_table_record", "declared_direct_patch", "unclassified_candidate")
    }
    return {
        "scan_range": f"0x000000..0x{SCAN_END:06X}",
        "candidate_count": len(rows),
        "modified_candidate_count": sum(bool(row["modified"]) for row in rows),
        "ownership_counts": counts,
        "warning": (
            "Candidates only match a conservative glyph/control/FFFF byte pattern. "
            "Unclassified candidates may be data and require ownership proof before patching."
        ),
        "candidates": rows,
    }


def markdown_report(result: dict[str, object]) -> str:
    counts = result["ownership_counts"]
    return "\n".join(
        [
            "# Direct Word-String Candidate Inventory",
            "",
            "Generated by `python3 tools/jp_direct_string_inventory.py`.",
            "",
            "The scanner accepts at least three Japanese glyph IDs (`0000..07FF`), known",
            "controls, and an `FFFF` terminator outside the scenario event blocks. A match is",
            "a candidate, not proof that the data is visible text.",
            "",
            f"- Scan range: `{result['scan_range']}`",
            f"- Candidates: {result['candidate_count']}",
            f"- Modified candidates: {result['modified_candidate_count']}",
            f"- Exact pointer-table records: {counts['pointer_table_record']}",
            f"- Existing declared direct patches: {counts['declared_direct_patch']}",
            f"- Unclassified candidates: {counts['unclassified_candidate']}",
            "",
            "Unclassified records must be rendered or cross-referenced from code before they are",
            "added to the builder. Detailed tokens and ownership are in",
            "`localization/direct_word_candidates.json`.",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Inventory conservative direct word-string candidates")
    parser.add_argument("--jp-rom", type=Path, default=Path("roms/original/Langrisser II (Japan).md"))
    parser.add_argument(
        "--ko-rom", type=Path, default=Path("roms/builds/Langrisser II (Korean JP Probe).md")
    )
    parser.add_argument("--json", type=Path, default=Path("localization/direct_word_candidates.json"))
    parser.add_argument("--markdown", type=Path, default=Path("docs/direct_word_candidate_inventory.md"))
    args = parser.parse_args()
    result = inventory(args.jp_rom.read_bytes(), args.ko_rom.read_bytes())
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(markdown_report(result), encoding="utf-8")
    print(
        f"{result['candidate_count']} candidates; "
        f"{result['ownership_counts']['unclassified_candidate']} unclassified"
    )


if __name__ == "__main__":
    main()
