#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


EVENT_POINTER_TABLE = 0x18011A
SCENARIO_COUNT = 31
EVENT_DATA_END = 0x1B9000
TEXT_CONTROLS = {0xFFF7, 0xFFFE}
TEXT_TERMINATORS = {0xFFFD, 0xFFFF}
MAX_GLYPH_ID = 0x07FF


def be16(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 2], "big")


def be32(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 4], "big")


def read_text_page(data: bytes, offset: int, limit: int) -> list[int] | None:
    words: list[int] = []
    glyph_count = 0
    for _ in range(256):
        if offset + 2 > limit:
            return None
        word = be16(data, offset)
        words.append(word)
        offset += 2
        if word in TEXT_TERMINATORS:
            return words if glyph_count >= 3 else None
        if word in TEXT_CONTROLS:
            continue
        if word > MAX_GLYPH_ID:
            return None
        glyph_count += 1
    return None


def event_block_starts(data: bytes) -> list[int]:
    starts = [
        be32(data, EVENT_POINTER_TABLE + index * 4)
        for index in range(SCENARIO_COUNT)
    ]
    if starts != sorted(starts) or not all(0x180000 <= value < EVENT_DATA_END for value in starts):
        raise ValueError("invalid or unordered event pointer table")
    return starts


def inventory(japanese: bytes, korean: bytes) -> dict[str, object]:
    starts = event_block_starts(japanese)
    scenarios: list[dict[str, object]] = []
    for number, (start, end) in enumerate(zip(starts, starts[1:] + [EVENT_DATA_END]), 1):
        pages: dict[int, dict[str, object]] = {}
        for source in range(start, end - 3, 2):
            target = be32(japanese, source)
            if not (start <= target < end) or target & 1:
                continue
            words = read_text_page(japanese, target, end)
            if words is None:
                continue
            page = pages.setdefault(
                target,
                {
                    "address": f"0x{target:06X}",
                    "word_count": len(words),
                    "terminator": f"0x{words[-1]:04X}",
                    "tokens": " ".join(f"{word:04X}" for word in words),
                    "source_refs": [],
                },
            )
            page["source_refs"].append(f"0x{source:06X}")

        modified = 0
        for target, page in pages.items():
            byte_count = int(page["word_count"]) * 2
            original = japanese[target : target + byte_count]
            patched = korean[target : target + byte_count]
            changed_words = sum(
                original[index : index + 2] != patched[index : index + 2]
                for index in range(0, byte_count, 2)
            )
            page["modified"] = bool(changed_words)
            page["modified_word_count"] = changed_words
            modified += bool(changed_words)

        ordered_pages = [pages[address] for address in sorted(pages)]
        scenarios.append(
            {
                "scenario": number,
                "block_start": f"0x{start:06X}",
                "block_end": f"0x{end:06X}",
                "page_count": len(ordered_pages),
                "modified_page_count": modified,
                "unchanged_page_count": len(ordered_pages) - modified,
                "pages": ordered_pages,
            }
        )

    return {
        "event_pointer_table": f"0x{EVENT_POINTER_TABLE:06X}",
        "event_data_end": f"0x{EVENT_DATA_END:06X}",
        "scenario_count": SCENARIO_COUNT,
        "page_count": sum(int(item["page_count"]) for item in scenarios),
        "modified_page_count": sum(int(item["modified_page_count"]) for item in scenarios),
        "scenarios": scenarios,
    }


def markdown_report(result: dict[str, object]) -> str:
    lines = [
        "# Full Localization Event Inventory",
        "",
        "Generated by `python3 tools/jp_event_inventory.py`.",
        "",
        "`modified` means that the current Korean build differs from the Japanese ROM at",
        "that page. It does not by itself prove that the whole page is translated or live-verified.",
        "",
        f"- Event pointer table: `{result['event_pointer_table']}`",
        f"- Scenarios: {result['scenario_count']}",
        f"- Candidate text pages: {result['page_count']}",
        f"- Modified candidate pages: {result['modified_page_count']}",
        "",
        "| Scenario | Event block | Pages | Modified | Unchanged | Status |",
        "| ---: | --- | ---: | ---: | ---: | --- |",
    ]
    for item in result["scenarios"]:
        modified = int(item["modified_page_count"])
        total = int(item["page_count"])
        status = "unstarted" if modified == 0 else ("modified" if modified < total else "all modified")
        lines.append(
            f"| {item['scenario']} | `{item['block_start']}..{item['block_end']}` | "
            f"{total} | {modified} | {item['unchanged_page_count']} | {status} |"
        )
    lines.extend(
        [
            "",
            "Detailed addresses, source references, terminators, and original glyph-token streams",
            "are stored in `localization/event_pages.json`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Inventory Japanese event text pages by scenario")
    parser.add_argument("--jp-rom", type=Path, default=Path("roms/original/Langrisser II (Japan).md"))
    parser.add_argument(
        "--ko-rom",
        type=Path,
        default=Path("roms/builds/Langrisser II (Korean JP Probe).md"),
    )
    parser.add_argument("--json", type=Path, default=Path("localization/event_pages.json"))
    parser.add_argument(
        "--markdown",
        type=Path,
        default=Path("docs/full_localization_inventory.md"),
    )
    args = parser.parse_args()

    result = inventory(args.jp_rom.read_bytes(), args.ko_rom.read_bytes())
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(markdown_report(result), encoding="utf-8")
    print(
        f"{result['page_count']} candidate pages, "
        f"{result['modified_page_count']} modified; wrote {args.json} and {args.markdown}"
    )


if __name__ == "__main__":
    main()
