#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

sys.path.append(str(Path(__file__).resolve().parents[1]))

from scripts.build_korean_jp_probe import ITEM_NAME_PATCHES, JP_FONT_BASE, GLYPH_BYTES
from tools.jp_byte_table_analyzer import KOREAN_CLASS_LABELS
from tools.scenario_data import KOREAN_NAME_BY_ID


CLASS_POINTER_TABLE = 0x05E6D6
CLASS_COUNT = 157
ITEM_POINTER_TABLE = 0x060364
ITEM_COUNT = 38
NAME_POINTER_TABLE = 0x0618E8
NAME_COUNT = 117

TABLES = (
    ("classes", CLASS_POINTER_TABLE, CLASS_COUNT),
    ("items", ITEM_POINTER_TABLE, ITEM_COUNT),
    ("names", NAME_POINTER_TABLE, NAME_COUNT),
)


def be32(data: bytes, offset: int) -> int:
    return int.from_bytes(data[offset : offset + 4], "big")


def read_ff_string(data: bytes, offset: int, limit: int = 64) -> bytes:
    end = data.find(b"\xff", offset, min(len(data), offset + limit))
    if end < 0:
        raise ValueError(f"missing FF terminator at 0x{offset:06X}")
    return data[offset:end]


def decode_cp932(raw: bytes) -> str:
    return raw.decode("cp932", errors="replace")


def target_for(table: str, index: int) -> str | None:
    if table == "classes":
        return KOREAN_CLASS_LABELS[index].strip()
    if table == "items":
        # This byte table has a blank entry at ID 0. ITEM_NAME_PATCHES indexes
        # the 37 normal items followed by one separate extra shop entry.
        return "" if index == 0 else ITEM_NAME_PATCHES[index - 1]
    return KOREAN_NAME_BY_ID.get(index)


def changed_font_codes(japanese: bytes, korean: bytes, raw: bytes) -> list[str]:
    changed = []
    for code in sorted(set(raw) - {0x20}):
        offset = JP_FONT_BASE + code * GLYPH_BYTES
        if japanese[offset : offset + GLYPH_BYTES] != korean[offset : offset + GLYPH_BYTES]:
            changed.append(f"0x{code:02X}")
    return changed


def inventory_table(
    japanese: bytes,
    korean: bytes,
    name: str,
    pointer_table: int,
    count: int,
) -> dict[str, object]:
    rows = []
    for index in range(count):
        original_pointer = be32(japanese, pointer_table + index * 4)
        current_pointer = be32(korean, pointer_table + index * 4)
        original = read_ff_string(japanese, original_pointer)
        current = read_ff_string(korean, current_pointer)
        font_codes = changed_font_codes(japanese, korean, original)
        raw_modified = original_pointer != current_pointer or original != current
        rows.append(
            {
                "id": index,
                "pointer": f"0x{original_pointer:06X}",
                "current_pointer": f"0x{current_pointer:06X}",
                "capacity": len(original),
                "original_hex": original.hex(" ").upper(),
                "original_text": decode_cp932(original),
                "current_hex": current.hex(" ").upper(),
                "target_korean": target_for(name, index),
                "raw_modified": raw_modified,
                "font_glyph_modified": bool(font_codes),
                "modified_font_codes": font_codes,
                "render_path_touched": raw_modified or bool(font_codes),
            }
        )
    return {
        "pointer_table": f"0x{pointer_table:06X}",
        "entry_count": count,
        "unique_string_count": len({row["pointer"] for row in rows}),
        "raw_modified_count": sum(bool(row["raw_modified"]) for row in rows),
        "font_glyph_modified_count": sum(bool(row["font_glyph_modified"]) for row in rows),
        "render_path_touched_count": sum(bool(row["render_path_touched"]) for row in rows),
        "known_korean_target_count": sum(row["target_korean"] is not None for row in rows),
        "entries": rows,
    }


def inventory(japanese: bytes, korean: bytes) -> dict[str, object]:
    return {
        "warning": (
            "A changed byte string or font glyph only proves that its render path was touched; "
            "it does not prove a correct translation or live verification."
        ),
        "tables": {
            name: inventory_table(japanese, korean, name, pointer, count)
            for name, pointer, count in TABLES
        },
    }


def markdown_report(result: dict[str, object]) -> str:
    unknown_name_targets = (
        int(result["tables"]["names"]["entry_count"])
        - int(result["tables"]["names"]["known_korean_target_count"])
    )
    lines = [
        "# Global String Localization Inventory",
        "",
        "Generated by `python3 tools/jp_global_inventory.py`.",
        "",
        "`raw modified` compares the pointer and FF-terminated byte string. `font glyph modified`",
        "means at least one original byte code now points at changed 16x16 global font pixels.",
        "Neither flag proves that the displayed result is translated or live-verified.",
        "",
        "| Table | Pointer table | Entries | Unique strings | Raw modified | Font glyph modified | Render path touched | Known KO targets |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for name, table in result["tables"].items():
        lines.append(
            f"| {name} | `{table['pointer_table']}` | {table['entry_count']} | "
            f"{table['unique_string_count']} | {table['raw_modified_count']} | "
            f"{table['font_glyph_modified_count']} | {table['render_path_touched_count']} | "
            f"{table['known_korean_target_count']} |"
        )
    lines.extend(
        [
            "",
            "Detailed IDs, original text/hex, capacities, targets, and changed font codes are in",
            "`localization/global_strings.json`.",
            "",
            "## Interpretation",
            "",
            "- Classes and names are shared by preparation, status, map, and editor paths.",
            "- The item byte table is separate from the relocated 16x16 item-name and description tables.",
            "- The Scenario 1 knife intentionally keeps its original byte codes while their glyph pixels render `단검`.",
            (
                f"- {unknown_name_targets} Korean name targets remain `null`; identify them from the Japanese ID before translation."
                if unknown_name_targets
                else "- All 117 name IDs now have source-based Korean targets; this does not mean every ROM render path is patched."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Inventory shared Japanese byte-string tables")
    parser.add_argument("--jp-rom", type=Path, default=Path("roms/original/Langrisser II (Japan).md"))
    parser.add_argument(
        "--ko-rom",
        type=Path,
        default=Path("roms/builds/Langrisser II (Korean JP Probe).md"),
    )
    parser.add_argument("--json", type=Path, default=Path("localization/global_strings.json"))
    parser.add_argument(
        "--markdown",
        type=Path,
        default=Path("docs/global_localization_inventory.md"),
    )
    args = parser.parse_args()
    result = inventory(args.jp_rom.read_bytes(), args.ko_rom.read_bytes())
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(markdown_report(result), encoding="utf-8")
    summary = ", ".join(
        f"{name} {table['raw_modified_count']}/{table['entry_count']} raw-modified"
        for name, table in result["tables"].items()
    )
    print(f"{summary}; wrote {args.json} and {args.markdown}")


if __name__ == "__main__":
    main()
