#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "localization/runtime_verification.json"
OUTPUT = ROOT / "docs/runtime_verification_inventory.md"
SCENARIO_COUNT = 31


def load_inventory(path: Path = INPUT) -> dict[str, object]:
    data = json.loads(path.read_text(encoding="utf-8"))
    states = data.get("states")
    surfaces = data.get("surfaces")
    scenarios = data.get("scenarios")
    if not isinstance(states, list) or not states or len(states) != len(set(states)):
        raise ValueError("states must be a non-empty unique list")
    if not isinstance(surfaces, list) or not surfaces or len(surfaces) != len(set(surfaces)):
        raise ValueError("surfaces must be a non-empty unique list")
    if not isinstance(scenarios, list) or len(scenarios) != SCENARIO_COUNT:
        raise ValueError(f"expected {SCENARIO_COUNT} scenario entries")

    expected_numbers = list(range(1, SCENARIO_COUNT + 1))
    actual_numbers = [entry.get("scenario") for entry in scenarios]
    if actual_numbers != expected_numbers:
        raise ValueError("scenario entries must be ordered 1..31")

    allowed_states = set(states)
    for entry in scenarios:
        for surface in surfaces:
            state = entry.get(surface, "pending")
            if state not in allowed_states:
                raise ValueError(
                    f"Scenario {entry['scenario']} {surface} has invalid state {state!r}"
                )
        captures = entry.get("captures", [])
        if not isinstance(captures, list) or any(
            not isinstance(capture, str) or not capture.startswith("captures/")
            for capture in captures
        ):
            raise ValueError(f"Scenario {entry['scenario']} has invalid captures")

    for evidence in data.get("global_evidence", []):
        if evidence.get("state") not in allowed_states:
            raise ValueError(
                f"global surface {evidence.get('surface')!r} has invalid state"
            )
        captures = evidence.get("captures", [])
        if not isinstance(captures, list) or any(
            not isinstance(capture, str) or not capture.startswith("captures/")
            for capture in captures
        ):
            raise ValueError(
                f"global surface {evidence.get('surface')!r} has invalid captures"
            )
    return data


def render_markdown(data: dict[str, object]) -> str:
    surfaces = data["surfaces"]
    scenarios = data["scenarios"]
    state_label = {
        "pending": "pending",
        "historical": "historical",
        "progressed_current": "progressed",
        "verified_current": "current",
        "verified_probe": "probe",
    }
    lines = [
        "# Runtime Verification Inventory",
        "",
        "Generated by `python3 tools/runtime_verification_inventory.py`.",
        "Static text modification is tracked separately and does not satisfy these live checks.",
        f"Production checksum: `{data['production_checksum']}`.",
        "",
        "States: `current` is visually reviewed production playback, `progressed`",
        "reached the endpoint on the current build without reviewing every intermediate",
        "page, `probe` is a documented production-derived probe, `historical` predates",
        "the current checksum, and `pending` has no accepted live evidence yet.",
        "",
        "| Scenario | " + " | ".join(surfaces) + " | Evidence |",
        "| ---: | " + " | ".join("---" for _ in surfaces) + " | ---: |",
    ]
    for entry in scenarios:
        values = [state_label[entry.get(surface, "pending")] for surface in surfaces]
        evidence_count = len(entry.get("captures", []))
        lines.append(
            f"| {entry['scenario']} | " + " | ".join(values) + f" | {evidence_count} |"
        )

    lines.extend(["", "## Evidence Notes", ""])
    for entry in scenarios:
        captures = entry.get("captures", [])
        note = entry.get("note")
        if not captures and not note:
            continue
        lines.append(f"### Scenario {entry['scenario']}")
        if note:
            lines.append("")
            lines.append(str(note))
        if captures:
            lines.append("")
            lines.extend(f"- `{capture}`" for capture in captures)
        lines.append("")

    lines.extend(["## Global Surface Evidence", ""])
    for evidence in data.get("global_evidence", []):
        lines.append(
            f"- `{evidence['surface']}`: {state_label[evidence['state']]} "
            f"checksum `{evidence['checksum']}` (base `{evidence['based_on']}`). "
            f"{evidence['note']}"
        )
        lines.extend(f"  - `{capture}`" for capture in evidence.get("captures", []))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    data = load_inventory()
    OUTPUT.write_text(render_markdown(data), encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
